import { Station } from '../types/journey';

export const LINE_2_STATIONS: Station[] = [
  { id: 'sindorim', name: '신도림', order: 0 },
  { id: 'dorimcheon', name: '도림천', order: 1 },
  { id: 'yangcheongu', name: '양천구청', order: 2 },
  { id: 'sinjeong', name: '신정네거리', order: 3 },
  { id: 'kkachisan', name: '까치산', order: 4 },
  { id: 'yeongdeungpogucheong', name: '영등포구청', order: 5 },
  { id: 'dangsan', name: '당산', order: 6 },
  { id: 'hapjeong', name: '합정', order: 7 },
  { id: 'hongik', name: '홍대입구', order: 8 },
  { id: 'sinchon', name: '신촌', order: 9 },
  { id: 'ewha', name: '이대', order: 10 },
  { id: 'ahyeon', name: '아현', order: 11 },
  { id: 'chungjeongno', name: '충정로', order: 12 },
  { id: 'siheung', name: '시청', order: 13 },
  { id: 'euljiro1', name: '을지로입구', order: 14 },
  { id: 'euljiro3', name: '을지로3가', order: 15 },
  { id: 'euljiro4', name: '을지로4가', order: 16 },
  { id: 'dongdaemun', name: '동대문역사문화공원', order: 17 },
  { id: 'sinseoldong', name: '신설동', order: 18 },
  { id: 'sindang', name: '신당', order: 19 },
  { id: 'sangwangsimnri', name: '상왕십리', order: 20 },
  { id: 'wangsimni', name: '왕십리', order: 21 },
  { id: 'hanyang', name: '한양대', order: 22 },
  { id: 'ttukseom', name: '뚝섬', order: 23 },
  { id: 'seongsu', name: '성수', order: 24 },
  { id: 'konkuk', name: '건대입구', order: 25 },
  { id: 'guui', name: '구의', order: 26 },
  { id: 'gangbyeon', name: '강변', order: 27 },
  { id: 'jamsillnaru', name: '잠실나루', order: 28 },
  { id: 'jamsil', name: '잠실', order: 29 },
  { id: 'jamsilsaenae', name: '잠실새내', order: 30 },
  { id: 'jonghap', name: '종합운동장', order: 31 },
  { id: 'samsung', name: '삼성', order: 32 },
  { id: 'seonreung', name: '선릉', order: 33 },
  { id: 'yeoksam', name: '역삼', order: 34 },
  { id: 'gangnam', name: '강남', order: 35 },
  { id: 'gyodae', name: '교대', order: 36 },
  { id: 'seocho', name: '서초', order: 37 },
  { id: 'bangbae', name: '방배', order: 38 },
  { id: 'sadang', name: '사당', order: 39 },
  { id: 'nakseongdae', name: '낙성대', order: 40 },
  { id: 'seouluniv', name: '서울대입구', order: 41 },
  { id: 'bongcheon', name: '봉천', order: 42 },
  { id: 'sinrim', name: '신림', order: 43 },
  { id: 'sindaebang', name: '신대방', order: 44 },
  { id: 'guro', name: '구로디지털단지', order: 45 },
  { id: 'daelim', name: '대림', order: 46 },
];

export const SUBWAY_LINES = [
  {
    id: 'line-2',
    name: '2호선',
    color: '#00A44A',
    stations: LINE_2_STATIONS,
    isCircular: true,
  },
];
